### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Tweake** [athombv/com.lg.webos#2]
tested using 0.10.0

```
TypeError: Cannot read property 'scanner' of undefined
at module.exports.init (/drivers/tv/driver.js:13:12)
at /homey-app/manager/drivers.js:150:31
at Array.forEach (native)
at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)
at /homey-app/manager/drivers.js:20:38
at /homey-app/homey.js:1:1080
at Array.forEach (native)
at Object.<anonymous> (/homey-app/homey.js:1:1058)
at emitNone (events.js:67:13)
at Object.emit (events.js:166:7)
Exit code: 0
```

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1
